### ISSUE TITLE
The training Erro of Semantic3D

### ISSUE THREAD

**Issue by Fan-QY** [azuki-miho/RFCR#6]
Hello, thank you very much for your outstanding and great work. I wanted to test the performance on Semantic8 except for reduced8, so I put them all in the "Data/Semantic3D/original_data" folder. However, when I am training, I get the following errors. What are the problems and how to fix them?
Thank you very much for your help.

```
root@7f0b80d27641:/RFCR/KPConv_deform_Semantic3D# CUDA_VISIBLE_DEVICES=0 python3 training_Semantic3D.py

Dataset Preparation
*******************
Preparation of untermaederbrunnen_station1_xyz_intensity_rgb
Preparation of neugasse_station1_xyz_intensity_rgb
Preparation of sg27_station2_intensity_rgb
Preparation of bildstein_station3_xyz_intensity_rgb
Preparation of castleblatten_station1_intensity_rgb
Preparation of MarketplaceFeldkirch_Station4_rgb_intensity-reduced
Preparation of sg27_station3_intensity_rgb
Preparation of domfountain_station1_xyz_intensity_rgb
Preparation of marketplacefeldkirch_station4_intensity_rgb
Preparation of untermaederbrunnen_station3_xyz_intensity_rgb
Preparation of domfountain_station2_xyz_intensity_rgb
Preparation of stgallencathedral_station1_intensity_rgb
Preparation of sg28_station2_intensity_rgb
Preparation of sg27_station9_intensity_rgb
Preparation of bildstein_station5_xyz_intensity_rgb
Preparation of sg27_station10_intensity_rgb
Preparation of sg28_station4_intensity_rgb
Preparation of sg28_station5_xyz_intensity_rgb
Preparation of sg27_station6_intensity_rgb
Preparation of sg27_station8_intensity_rgb
Preparation of sg27_station4_intensity_rgb
Preparation of bildstein_station1_xyz_intensity_rgb
Preparation of domfountain_station3_xyz_intensity_rgb
Preparation of StGallenCathedral_station6_rgb_intensity-reduced
Preparation of marketplacefeldkirch_station1_intensity_rgb
Preparation of birdfountain_station1_xyz_intensity_rgb
Preparation of stgallencathedral_station3_intensity_rgb
Preparation of sg27_station10_rgb_intensity-reduced
Preparation of sg27_station1_intensity_rgb
Preparation of castleblatten_station5_xyz_intensity_rgb
Preparation of marketplacefeldkirch_station7_intensity_rgb
Preparation of sg27_station5_intensity_rgb
Preparation of sg28_Station2_rgb_intensity-reduced
Preparation of stgallencathedral_station6_intensity_rgb

Preparing KDTree for all scenes, subsampled at 0.060
[##############################] 100.0%

Preparing reprojection indices for validation and test
[##############################] 100.0%

Initiating input pipelines
WARNING:tensorflow:From /RFCR/KPConv_deform_Semantic3D/datasets/common.py:1015: calling reduce_min (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
2022-05-16 23:07:40.299533: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: NVIDIA TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:91:00.0
totalMemory: 11.90GiB freeMemory: 11.20GiB
2022-05-16 23:07:40.300995: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2022-05-16 23:07:41.532863: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2022-05-16 23:07:41.532932: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2022-05-16 23:07:41.532942: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2022-05-16 23:07:41.535327: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10835 MB memory) -> physical GPU (device: 0, name: NVIDIA TITAN Xp, pci bus id: 0000:91:00.0, compute capability: 6.1)
Calib Neighbors 00000001 : timings 160.67 16.56
Calib Neighbors 00000007 : timings 63.17 20.49
Calib Neighbors 00000014 : timings 207.37 34.86


Creating Model
**************

class weight
[1.3082228 1.2470493 1.        1.7501997 1.0041255 1.9499791 2.0542078
 2.0797122]
Tensor("loss/Shape:0", shape=(?,), dtype=int32)
Tensor("loss/Shape_1:0", shape=(?,), dtype=int32)
/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gradients_impl.py:112: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
2022-05-16 23:08:07.719663: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2022-05-16 23:08:07.719716: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2022-05-16 23:08:07.719723: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2022-05-16 23:08:07.719729: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2022-05-16 23:08:07.719799: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10835 MB memory) -> physical GPU (device: 0, name: NVIDIA TITAN Xp, pci bus id: 0000:91:00.0, compute capability: 6.1)

----------------
Done in 21.7 s
----------------

Start Training
**************

Caught a NaN error :
3
indices[20506,6] = 73654 is not in [0, 73654)
	 [[node inputs/GatherV2 (defined at /RFCR/KPConv_deform_Semantic3D/models/KPFCNN_model.py:75)  = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](inputs/Cast/_241, IteratorGetNext:10, optimizer/gradients/KernelPointNetwork/layer_0/resnetb_strided_2/shortcut/concat_grad/GatherV2_1/axis)]]
name: "inputs/GatherV2"
op: "GatherV2"
input: "inputs/Cast"
input: "IteratorGetNext:10"
input: "inputs/GatherV2/axis"
attr {
  key: "Taxis"
  value {
    type: DT_INT32
  }
}
attr {
  key: "Tindices"
  value {
    type: DT_INT32
  }
}
attr {
  key: "Tparams"
  value {
    type: DT_INT32
  }
}

inputs/GatherV2
['inputs/Cast:0', 'IteratorGetNext:10', 'inputs/GatherV2/axis:0']
['inputs/GatherV2:0']
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[20506,6] = 73654 is not in [0, 73654)
	 [[{{node inputs/GatherV2}} = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](inputs/Cast/_241, IteratorGetNext:10, optimizer/gradients/KernelPointNetwork/layer_0/resnetb_strided_2/shortcut/concat_grad/GatherV2_1/axis)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/RFCR/KPConv_deform_Semantic3D/utils/trainer.py", line 246, in train
    _, L_out, L_reg, L_p, probs, labels, acc = self.sess.run(ops, {model.dropout_prob: 0.5})
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[20506,6] = 73654 is not in [0, 73654)
	 [[node inputs/GatherV2 (defined at /RFCR/KPConv_deform_Semantic3D/models/KPFCNN_model.py:75)  = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](inputs/Cast/_241, IteratorGetNext:10, optimizer/gradients/KernelPointNetwork/layer_0/resnetb_strided_2/shortcut/concat_grad/GatherV2_1/axis)]]

Caused by op 'inputs/GatherV2', defined at:
  File "training_Semantic3D.py", line 210, in <module>
    model = KernelPointFCNN(dataset.flat_inputs, config)
  File "/RFCR/KPConv_deform_Semantic3D/models/KPFCNN_model.py", line 75, in __init__
    tmp_onehot_label = tf.gather(self.onehot_labels[tmp_layer], self.inputs['pools'][tmp_layer])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/array_ops.py", line 2675, in gather
    return gen_array_ops.gather_v2(params, indices, axis, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 3332, in gather_v2
    "GatherV2", params=params, indices=indices, axis=axis, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): indices[20506,6] = 73654 is not in [0, 73654)
	 [[node inputs/GatherV2 (defined at /RFCR/KPConv_deform_Semantic3D/models/KPFCNN_model.py:75)  = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](inputs/Cast/_241, IteratorGetNext:10, optimizer/gradients/KernelPointNetwork/layer_0/resnetb_strided_2/shortcut/concat_grad/GatherV2_1/axis)]]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "training_Semantic3D.py", line 234, in <module>
    trainer.train(model, dataset)
  File "/RFCR/KPConv_deform_Semantic3D/utils/trainer.py", line 357, in train
    a = 1/0
ZeroDivisionError: division by zero
```

**Comment by azuki-miho** [comment]
Thanks for your question. Even though we only test our code in the Semantic3D reduced-8 dataset, I can offer some hints to solve this problem. This problem seems to occur when extracting labels from previous layers during target RFCC generation. You can check the values of self.inputs['pools'][tmp_layer] and the sive of the previous point cloud to check whether some index is larger than the  size of sub-point-cloud?

**Comment by MarcusnHuang** [comment]
Hello, I also encountered the same problem, how did you solve it in the end?

**Comment by azuki-miho** [comment]
It seems you utilize the KPConv backbone, whether it is possible to run the code with naive KPConv?

**Comment by MarcusnHuang** [comment]
I want to use my own dataset for training, which has been successfully implemented on the KPConv network, and I want to experiment on RFCR as well, but I have encountered a problem and am here to ask for help.
Here's my error log.
Start Training
**************

Caught a NaN error :
3
indices[2584,14] = 11650 is not in [0, 11650)
         [[node inputs/GatherV2 (defined at /share/home/wangyongjun/wangyongjun_tangjh/hzh/RFCR-master/KPConv_deform_Semantic3D/models/KPFCNN_model.py:83)  = GatherV2[Taxis=DT_INT32, Tindices=DT_INT32, Tparams=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](inputs/Cast/_235, IteratorGetNext:10, optimizer/gradients/KernelPointNetwork/layer_0/resnetb_strided_2/shortcut/concat_grad/GatherV2_1/axis)]]
name: "inputs/GatherV2"
op: "GatherV2"
input: "inputs/Cast"
input: "IteratorGetNext:10"
input: "inputs/GatherV2/axis"
attr {
  key: "Taxis"
  value {
    type: DT_INT32
  }
}
attr {
  key: "Tindices"
  value {
    type: DT_INT32
  }
}
attr {
  key: "Tparams"
  value {
    type: DT_INT32
  }
}

inputs/GatherV2
['inputs/Cast:0', 'IteratorGetNext:10', 'inputs/GatherV2/axis:0']
['inputs/GatherV2:0']

**Comment by MarcusnHuang** [comment]
Hello, this problem has been bothering me for several days, can you help me, please?

**Comment by azuki-miho** [comment]
As RFCR is relatively simple to implement and only a few lines of code should be inserted into the backbone, whether it is possible to first run the code and then insert the code?

**Comment by MarcusnHuang** [comment]
Thank you for your reply, but I can't clearly understand what you mean, is it to delete the RFCR module running code, and then add it, then isn't that the backbone of KPConv? And could this indexing problem be caused by the dataset category?

**Comment by azuki-miho** [comment]
Actually, I think you should first check where the problem from, the Dataset, the KPConv backbone or the RFCR module, and the solve the problem.

**Comment by MarcusnHuang** [comment]
First of all, thank you very much, since I have successfully applied my dataset to the KPConv original network, so I guess it is the RFCR module issue.

**Comment by azuki-miho** [comment]
As the KPConv original network, whether it is possible to add the RFCC generation, RFCC supervision, and Feature Densification separately and locate the problem.
